### ISSUE TITLE
Pingback is not defined in the rel registry (from #3)

### ISSUE THREAD

**Issue by kevinmarks** [w3c-social/webmention#8] opened 2015-11-26 00:07 UTC
The IANA registry is not used for HTML rels. 
The [existing-rels](http://microformats.org/wiki/existing-rel-values#webmention) registry has been [updated](http://microformats.org/wiki/index.php?title=existing-rel-values&diff=prev&oldid=65323) with the current specification link.

**Comment by tantek** [comment] 2015-11-26 00:24
Updating title as I think "webmention" was intended, not "pingback". Noting that @kevinmarks also resolved the issue by updating the rel registry thus closing as handled.

**Closed by tantek** 2015-11-26 00:24 UTC

**Comment by kevinmarks** [comment] 2015-11-26 00:39
Yes, sorry was trying to capture the important bit of that discussion. Pingback *is* in existing rels as well http://microformats.org/wiki/existing-rel-values#pingback

**Comment by elf-pavlik** [comment] 2015-11-28 12:48
As I already explained in https://github.com/converspace/webmention/issues/38

> The webmention endpoint is advertised in the HTTP Link header or a <link> or &lt;a&gt; element with rel="webmention" . If more than one of these is present, the HTTP Link header takes precedence, followed by the <link> element, and finally the &lt;a&gt; element. Clients MUST support all three options and fall back in this order.

Microformats wiki registry applies only to HTML5 and **not to HTTP Link header**. IANA registry will have new workflow soon which we should use: https://github.com/mnot/I-D/issues/40 | https://github.com/mnot/I-D/commit/9da94377a8cceab40b401fcaa81a832a29dbf3c2

Would you like to reopen this issue or I should start a new one?

**Comment by aaronpk** [comment] 2016-03-19 17:07
Webmention is in the HTML rel registry on microformats.org, and is now also pending IANA registration via #30. @kevinmarks can I mark this issue as "commenter satisfied"?

**Comment by kevinmarks** [comment] 2016-03-19 17:10
Yes, I thought this was closed when the IANA issue was opened.
